### PR TITLE
[ANALYZER-3726]-No points on the Geo map despite the fact that New Zealand have values for City level

### PR DESCRIPTION
**Pull request by denisprotopopov**
-fixed

### CODE REVIEW

**Comment by denisprotopopov** [comment]
alternative https://github.com/pentaho/pentaho-platform-plugin-geo/pull/252

**Comment by denisprotopopov** [comment]
@mbatchelor could you please look at it

**Comment by marcbatchelor-nucleus** [comment]
@carlosrusso - I prefer this fix to the pentaho-platform-plugin-geo fix proposed. Thoughts ?

**Comment by carlosrusso** [comment]
@mbatchelor I also thought you would prefer this one, and indeed it is the correct thing to do.

I'm assuming we'll have to do a version bump as well.

As such, you need to know that this fix has an indirect impact on the GeoMap viz bundled with DET (the vizAPI 3) version: we should check if this fix does not have secondary effects on DET.

Because `pentaho-platform-plugin-geo` is including a minified version of OpenLayers directly, and publishing it as an artifact, we need to update `pentaho-platform-plugin-geo` with a fresh version of `OpenLayers.js`.

**Review by carlosrusso — APPROVED** [review]
This is fine.

Because `pentaho-platform-plugin-geo` is including a minified version of OpenLayers directly, and publishing it as an artifact, we need to update `pentaho-platform-plugin-geo` with a fresh version of `OpenLayers.js`.

This means we'll have to update the `release` branch with this fix and do a version bump (on `lib/OpenLayers.js`)

Because there is no build in place for OpenLayers, someone will have to use the closure compiler to generate the new minified version of OpenLayers, and place it in `pentaho-platform-plugin-geo`

**Pull request merged**
